# Generated by Django 3.2.8 on 2022-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'required': 'Enter First Name First'}, max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
