# Generated by Django 3.2.8 on 2022-03-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(default=0, upload_to='stuimage'),
            preserve_default=False,
        ),
    ]
