# Generated by Django 3.2.8 on 2022-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountdata', '0003_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': 'Enter First Name First'}, max_length=15)),
                ('heading', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
