# Generated by Django 3.2.8 on 2022-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountdata', '0004_auto_20220405_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='heading',
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(error_messages={'required': 'Enter First Name First'}, max_length=30),
        ),
    ]
