# Generated by Django 3.2.8 on 2022-04-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountdata', '0005_auto_20220406_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
