# Generated by Django 3.2.8 on 2022-04-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountdata', '0006_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(error_messages={'required': 'Enter First Name First'}, max_length=30)),
                ('writter', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=130)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content1', models.TextField()),
            ],
        ),
    ]
